### ISSUE TITLE
How to know the piece_kind can be used for hands

### ISSUE THREAD

**Issue by sugyan** [rust-shogi-crates/shogi_core#14]
Or, it would be helpful if there is a way to enumerate only `PieceKind`s that could be used for hands, such as `PieceKind::all_hands()`.

**Comment by koba-e964** [comment]
I don't have a concrete idea of what this feature should look like yet, but I understand the necessity of this feature.
Until this feature is stabilized, I'd like to ask you to use [`Hand::new().count(piece_kind).is_some()`](https://docs.rs/shogi_core/latest/shogi_core/struct.Hand.html#method.count) instead.

I am planning to export the following items at least:
- `7` (the number of valid `PieceKind`s in hand)
- `fn ...(piece_kind: PieceKind) -> bool { piece_kind as u8 <= 7 }` (droppability)

Submodules in this crate has a strict dependency relation, and `Hand` depends on `PieceKind` but not the other way around; so I'm planning to place these items in `Hand`.
